var arrayCleaner = require('../helpers/array-cleaner');

primaryWords = [
    "Amadeus         ",                                   
    "Employee Data Model  ",                              
    "API.ai Data Adapter  ",                              
    "Weather Bot Data Adapter ",                          
    "SmallTalk Bot Data Adapter ",                        
    "AccuWeather ",                                       
    "Github",                                             
    "Places App Data Model",                              
    "Google URL Shortener",                               
    "Weather",                                            
    "Places Data (Google)",                               
    "Trello",                                             
    "Google Calendar",                                    
    "The New York Times Best Sellers",                    
    "GoToMeeting",                                        
    "Horizontal Parallax",                                
    "Employee Directory",                                 
    "Sliding Menu",                                       
    "Skeleton Screen",                                    
    "Vertical Parallax ",                                 
    "Rating Prompt",                                      
    "Animated Text Field",                                
    "Floating Action",                                    
    "Range Slider",                                       
    "Single Slider",                                      
    "Login",                                             
    "Single Date Picker",                                 
    "Date Range Picker",                                  
    "List-Details (Employee)",                            
    "Place Locator",                                      
    "Refresh Animation (Generic)",                        
    "Refresh Animation (Travel)",                         
    "Progress Bar - Check (Theme 1)",                     
    "Progress Bar - Circle (Theme 1)",                    
    "Refresh Animation(Shopping Cart)",                   
    "Vertical Bar Chart",                                 
    "Horizontal Bar Charts",                              
    "Refresh Animation (Rotating Objects)",               
    "Refresh Animation (Falling Objects)",                
    "Interstitial Screen (Animated Squares)",            
    "Interstitial Screen (Travel)",                       
    "Interstitial Screen (Shopping)",                     
    "Interstitial Screen (Bouncing Object)",              
    "Interstitial Screen (Ripples)",                      
    "Facebook Data Adapter",                              
    "Taxamo Data Adapter",                                
    "Linkedin Data Adapter",                              
    "Botlytics Data Adapter",                             
    "Bit.ly",                                             
    "Chatbot",                                            
    "PayPal",                                             
    "Google Translate",                                   
    "Rating and Feedback Prompt",                         
    "Progress Bar - Shopping (Theme1)",                   
    "Progress Bar - Shopping (Theme 2)",                  
    "Progress Bar - Finance (Theme 2)",                  
    "Sliding Feedback Prompt",                           
    "Progress Bar - Travel (Theme 2)",                    
    "Generic Feedback Prompt",                            
    "Progress Bar - Arrow (Theme 2)",                     
    "Progress Bar - Check (Theme 2)",                     
    "Progress Bar - Circle (Theme 2)",                    
    "Tabs (Text with focus-Line)",                        
    "Tabs (Icon)",                                        
    "Tabs (Icon with Text)",                              
    "Tabs (Icon with focus-Circle)",                      
    "Tabs (Text with focus-Arrow)",                       
    "Tabs (Text with focus-Button and Shell)",            
    "Tabs (Text with focus-Button)",                      
    "Tabs (Text with focus-Arrow and Underline)",        
    "Progress Bar - Arrow (Theme 1)",                     
    "Progress Bar - Travel (Theme 1)",                    
    "Refresh Animation (Wave)",                           
    "Line Chart",                                         
    "Line Chart with Area",                               
    "Horizontal Bar Chart – Distributed Series",          
    "Vertical Bar Chart – Distributed Series",            
    "Doughnut Chart - Full Circle",                       
    "Donut Chart - Half Circle at 180 mark",              
    "Doughnut Chart - Inverse Half Circle",               
    "Pie Chart",                                          
    "Interstitial Screen (Business)",                     
    "Google Cloud Speech",                                
    "Action Sheet",                                       
    "Pie Chart – Partial Data",                           
    "Line Chart - Multi Series",                          
    "Horizontal Bar Chart - Multi Series",                
    "Vertical Bar Chart - Multi Series",                  
    "Line Chart - Scatter Plot",                          
    "Bipolar Area Chart",                                 
    "Horizontal Bar Chart - Stacked Bars",                
    "Vertical Bar Chart - Stacked Bars",                  
    "Horizontal Chart – Progress Bar with Text at End",   
    "Horizontal Chart - Progress Bar with Text on Bar",   
    "Work Order Management",                              
    "Kony Fabric Messaging Demo Application",             
    "Blogger",                                            
    "GettyImages",                                        
    "Alert Popup",                                        
    "Confirmation Popup",                                 
    "Input Prompt Popup",                                 
    "Login - Basic",                                      
    "List View - Docs",                                   
    "WorkOrder Data Model",                               
    "Kony Open Banking Data Model",                       
    "Bing Video Search",                                  
    "Bing",                                               
    "Bing Web Search",                                    
    "Bing News Search",                                   
    "Bing Image Search",                                  
    "Bing Auto Suggest",                                 
    "Open Banking",                                       
    "Kony Fabric Engagement Services",                    
    "Cardless Cash",                                      
    "MX Next Generation PFM",                             
    "Document ePresentment",                              
    "Facebook Login",                                     
    "LinkedIn Login",                                     
    "Office365 Login",                                    
    "PDF Viewer",                                         
    "Facebook OAuth Adapter",                             
    "Linkedin OAuth Adapter",                             
    "Daon Voice Authentication",                          
    "Google Login",                                       
    "Fingerprint Authentication",                         
    "Gemalto Face-ID",                                    
    "Product List &amp; Details",                         
    "Accordion",                                          
    "Google Sheets Backend Services",                     
    "SMS/ Text Message (Phone)",                          
    "Call (phone)",                                      
    "Zendes",                                            
    "Email",                                             
    "Jumio - Netverif",                                  
    "News and Weather",                                   
    "File Gallery Sample App",                           
    "Alexa Skills",                                       
    "Web Push Notifications",                             
    "Voice Output Interface",                             
    "Voice Input Interface",                              
    "Redux Integration Sample",                           
    "Box Data Adapter",                                   
    "Segment Widget Feature App ",                        
    "GeoLocation Feature App",                            
    "Interana Integration - Premium Analytics",           
    "Progressive Web App Example Output",                 
    "Google Sheets data driven app",                      
    "File System Adapter",                                
    "Launch Google Maps/ Apple Map",                      
    "Get Directions using Google Maps/Apple Maps",        
    "Barcode Generator",                                  
    "QR Code Generator",                                  
    "Skeleton Screen Template - Segment",                 
    "Timeline",                                           
    "Barcode/ QR Code Scanner",                           
    "Google Pay",                                         
    "Apple Pay",                                          
    "Google Sheets Collection"                         
];

module.exports = arrayCleaner(primaryWords);