var arrayCleaner = require('../helpers/array-cleaner');

secondaryWords = [
    "Hang",
    "Crash",
    "Bug",
    "Not working",
    "Not responding",
    "Not behaving",
    "Weird",
    "Unexpected behaviour",
    " fail",
    " failure ",
    "error",
    "stuck",
    "Suspend",
    "Suspended",
    "Idle",
    "No response",
    "Not responding",
    "Detach",
    "Remove",
    "Loss",
    "Creepy",
    "Strange",
    "Deviate",
    "Odd",
    "Silly",
    "Bizarre",
    "Decline",
    "Blunder",
    "Missed",
    "wrong",
    "Badly",
    "Disaster",
    "Abort",
    "Quit",
    "Interrupt", 
    "Terminate",
    "Stop running",
    "Disappoint"
];

module.exports = arrayCleaner(secondaryWords);